/* Generated By:JavaCC: Do not edit this line. Babel2009TokenManager.java */
import java.io.*;
import java.util.*;
import taulasimbols.*;

/** Token Manager. */
public class Babel2009TokenManager implements Babel2009Constants
{
  public static void CommonTokenAction(Token matchedToken)
  {
    Babel2009.escriuSortida(matchedToken);
  }

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x70000000L) != 0L)
         {
            jjmatchedKind = 60;
            return 23;
         }
         if ((active0 & 0x100L) != 0L)
            return 31;
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 46;
            return 0;
         }
         if ((active0 & 0x1fc000L) != 0L)
         {
            jjmatchedKind = 60;
            return 9;
         }
         if ((active0 & 0x78f203000L) != 0L)
         {
            jjmatchedKind = 60;
            return 63;
         }
         if ((active0 & 0xc00000L) != 0L)
         {
            jjmatchedKind = 60;
            return 28;
         }
         if ((active0 & 0xe00L) != 0L)
         {
            jjmatchedKind = 60;
            return 5;
         }
         return -1;
      case 1:
         if ((active0 & 0x30001000L) != 0L)
            return 63;
         if ((active0 & 0x40L) != 0L)
            return 1;
         if ((active0 & 0x7cfffee00L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 60;
               jjmatchedPos = 1;
            }
            return 63;
         }
         return -1;
      case 2:
         if ((active0 & 0x305004000L) != 0L)
            return 63;
         if ((active0 & 0x4eaffae00L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 2;
            return 63;
         }
         return -1;
      case 3:
         if ((active0 & 0xa0080000L) != 0L)
            return 63;
         if ((active0 & 0x44af7ae00L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 3;
            return 63;
         }
         return -1;
      case 4:
         if ((active0 & 0x220c00L) != 0L)
            return 63;
         if ((active0 & 0x44ad5a200L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 4;
            return 63;
         }
         return -1;
      case 5:
         if ((active0 & 0x4a40a000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 5;
            return 63;
         }
         if ((active0 & 0x400950200L) != 0L)
            return 63;
         return -1;
      case 6:
         if ((active0 & 0x408000L) != 0L)
            return 63;
         if ((active0 & 0x4a002000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 6;
            return 63;
         }
         return -1;
      case 7:
         if ((active0 & 0xa002000L) != 0L)
            return 63;
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 7;
            return 63;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 47:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 65:
      case 97:
         return jjStartNfaWithStates_0(0, 8, 31);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0xe00L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1fc000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0xc00000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x3000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0xc000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x70000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x700000000L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(1, 6, 1);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x300000200L);
      case 69:
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(1, 12, 63);
         return jjMoveStringLiteralDfa2_0(active0, 0x40d004000L);
      case 73:
      case 105:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x200f8400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x800L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x82000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40100000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000a400L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 70:
      case 102:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(2, 26, 63);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80200000L);
      case 76:
      case 108:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 63);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x20100800L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000L);
      case 82:
      case 114:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 14, 63);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 24, 63);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(2, 33, 63);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x20200L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x2800000L);
      case 73:
      case 105:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 63);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 77:
      case 109:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 63);
         break;
      case 79:
      case 111:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 63);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x42000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x440000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x40008000L);
      case 69:
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 63);
         break;
      case 73:
      case 105:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 63);
         return jjMoveStringLiteralDfa5_0(active0, 0x902000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x10200L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x400440000L);
      case 82:
      case 114:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 17, 63);
         return jjMoveStringLiteralDfa5_0(active0, 0xa000000L);
      case 84:
      case 116:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 63);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 9, 63);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 67:
      case 99:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 16, 63);
         break;
      case 71:
      case 103:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 63);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000L);
      case 79:
      case 111:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 63);
         break;
      case 82:
      case 114:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 63);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 34, 63);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
      case 69:
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 63);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 83:
      case 115:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 63);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 25, 63);
         break;
      case 69:
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 63);
         break;
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 82:
      case 114:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(7, 27, 63);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(8, 30, 63);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 64;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     jjCheckNAdd(61);
                  }
                  else if (curChar == 60)
                     jjCheckNAddTwoStates(14, 60);
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 57;
                  else if (curChar == 44)
                  {
                     if (kind > 56)
                        kind = 56;
                  }
                  else if (curChar == 41)
                  {
                     if (kind > 55)
                        kind = 55;
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  else if (curChar == 58)
                  {
                     if (kind > 53)
                        kind = 53;
                  }
                  else if (curChar == 59)
                  {
                     if (kind > 52)
                        kind = 52;
                  }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 46;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 61)
                  {
                     if (kind > 48)
                        kind = 48;
                  }
                  else if (curChar == 47)
                  {
                     if (kind > 46)
                        kind = 46;
                  }
                  else if (curChar == 42)
                  {
                     if (kind > 45)
                        kind = 45;
                  }
                  else if (curChar == 62)
                     jjCheckNAdd(14);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(12, 13);
                  if (curChar == 38)
                  {
                     if (kind > 47)
                        kind = 47;
                  }
                  else if (curChar == 45)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 43)
                  {
                     if (kind > 43)
                        kind = 43;
                  }
                  else if (curChar == 60)
                  {
                     if (kind > 38)
                        kind = 38;
                  }
                  else if (curChar == 62)
                  {
                     if (kind > 38)
                        kind = 38;
                  }
                  else if (curChar == 61)
                     jjCheckNAdd(14);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 28:
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 0:
                  if (curChar != 47)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0xffffffffffffc3ffL & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(1);
                  break;
               case 11:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 12:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 13:
                  if (curChar == 34 && kind > 37)
                     kind = 37;
                  break;
               case 14:
                  if (curChar == 61 && kind > 38)
                     kind = 38;
                  break;
               case 15:
                  if (curChar == 61)
                     jjCheckNAdd(14);
                  break;
               case 16:
               case 60:
                  if (curChar == 62 && kind > 38)
                     kind = 38;
                  break;
               case 17:
                  if (curChar == 60 && kind > 38)
                     kind = 38;
                  break;
               case 18:
                  if (curChar == 62)
                     jjCheckNAdd(14);
                  break;
               case 38:
                  if (curChar == 43 && kind > 43)
                     kind = 43;
                  break;
               case 39:
                  if (curChar == 45 && kind > 44)
                     kind = 44;
                  break;
               case 40:
                  if (curChar == 42 && kind > 45)
                     kind = 45;
                  break;
               case 41:
                  if (curChar == 47 && kind > 46)
                     kind = 46;
                  break;
               case 42:
                  if (curChar == 38 && kind > 47)
                     kind = 47;
                  break;
               case 43:
                  if (curChar == 61 && kind > 48)
                     kind = 48;
                  break;
               case 44:
                  if (curChar == 61 && kind > 49)
                     kind = 49;
                  break;
               case 45:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 61 && kind > 50)
                     kind = 50;
                  break;
               case 47:
                  if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 61 && kind > 51)
                     kind = 51;
                  break;
               case 49:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 59 && kind > 52)
                     kind = 52;
                  break;
               case 51:
                  if (curChar == 58 && kind > 53)
                     kind = 53;
                  break;
               case 52:
                  if (curChar == 40 && kind > 54)
                     kind = 54;
                  break;
               case 53:
                  if (curChar == 41 && kind > 55)
                     kind = 55;
                  break;
               case 54:
                  if (curChar == 44 && kind > 56)
                     kind = 56;
                  break;
               case 57:
                  if (curChar == 46 && kind > 59)
                     kind = 59;
                  break;
               case 58:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(14, 60);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  jjCheckNAdd(61);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  else if (curChar == 93)
                  {
                     if (kind > 58)
                        kind = 58;
                  }
                  else if (curChar == 91)
                  {
                     if (kind > 57)
                        kind = 57;
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  else if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 23:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(63);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 1:
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x10000000100000L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 4:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if ((0x8000000080000L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 8:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 12:
                  jjAddStates(0, 1);
                  break;
               case 19:
                  if ((0x4000000040000L & l) != 0L && kind > 39)
                     kind = 39;
                  break;
               case 20:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if ((0x800000008L & l) != 0L && kind > 39)
                     kind = 39;
                  break;
               case 26:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0x1000000010L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 32:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x4000000040000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 34:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if ((0x10000000100000L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 36:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 55:
                  if (curChar == 91 && kind > 57)
                     kind = 57;
                  break;
               case 56:
                  if (curChar == 93 && kind > 58)
                     kind = 58;
                  break;
               case 62:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               case 63:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(63);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 12:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 64 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   12, 13, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0x0L, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x80L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[64];
static private final int[] jjstateSet = new int[128];
static protected char curChar;
/** Constructor. */
public Babel2009TokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public Babel2009TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 64; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      CommonTokenAction(matchedToken);
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002700L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 63)
   {
      jjmatchedKind = 63;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         CommonTokenAction(matchedToken);
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
